FROM node:22.15-slim
WORKDIR /app

ENV NODE_ENV=production
COPY package*.json ./
RUN npm install --production && npm install ts-node typescript -D

COPY . .

EXPOSE 3000
CMD ["npx", "ts-node", "server/index.ts"]