services:
  db:
    image: mysql:8.4.5
    container_name: haibane_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: haibane_api
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '3001:3000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: haibane_frontend
    restart: on-failure
    ports:
      - '3000:3000'
    depends_on:
      - api
    command: npm run dev

volumes:
  db_data:
