FROM node:22.15-slim
WORKDIR /app

COPY package*.json nuxt.config.ts tsconfig.json ./
COPY app.vue ./
COPY public ./public
COPY server/api/hello.ts ./server/api/hello.ts

RUN npm install
RUN npm run build

EXPOSE 3000
CMD ["npm", "run", "start"]